apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: erp-system
spec:
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-exporter
  namespace: erp-system
spec:
  selector:
    app: mongodb-exporter
  ports:
    - port: 9216
      targetPort: 9216
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: erp-system
spec:
  selector:
    app: auth-service
  ports:
    - port: 3101
      targetPort: 3101
---
apiVersion: v1
kind: Service
metadata:
  name: core-service
  namespace: erp-system
spec:
  selector:
    app: core-service
  ports:
    - port: 3102
      targetPort: 3102
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: erp-system
spec:
  selector:
    app: api-gateway
  ports:
    - port: 3104
      targetPort: 3104
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: erp-system
spec:
  selector:
    app: frontend
  ports:
    - port: 3105
      targetPort: 3105
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: n8n
  namespace: erp-system
spec:
  selector:
    app: n8n
  ports:
    - port: 5678
      targetPort: 5678
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: erp-system
spec:
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: erp-system
spec:
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: sonarqube-db
  namespace: erp-system
spec:
  selector:
    app: sonarqube-db
  ports:
    - port: 5432
      targetPort: 5432