
services:

  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"

  auth-service:
    build: ./services/auth-service
    container_name: auth-service
    ports:
      - "3101:3101"
    environment:
      MONGO_URI: mongodb://root:rootpassword@mongo:27017/core-service?authSource=admin
      JWT_SECRET: ma_super_secrete
    depends_on:
      - mongo

  core-service:
    build: ./services/core-service
    container_name: core-service
    ports:
      - "3102:3102"
    environment:
      MONGO_URI: mongodb://root:rootpassword@mongo:27017/core-service?authSource=admin
    depends_on:
      - mongo

  api-gateway:
    build: ./services/api-gateway
    container_name: api-gateway
    ports:
      - "3104:3104"
    environment:
      MONGO_URI: mongodb://root:rootpassword@mongo:27017/core-service?authSource=admin
      JWT_SECRET: ma_super_secrete
    depends_on:
      - auth-service
      - core-service

  frontend:
    build: ./erp-ui
    container_name: frontend
    ports:
      - "3105:3105"
    depends_on:
      - api-gateway

volumes:
  mongo-data: