sonar.host.url=http://127.0.0.1:9000
sonar.token=sqp_1fa38144a4f0aefc8c547bb0897c4f1246bbe4c1

sonar.projectKey=Cristal_ERP
sonar.projectName=Cristal_ERP


sonar.sources=services

sonar.exclusions=**/node_modules/**,**/*.exe,**/*.zip