sonar.host.url=http://127.0.0.1:9000
sonar.token=squ_3a3ca58540fec929f52ef0fb2999530910e2ac93

# Utilisez la clé existante
sonar.projectKey=Cristal_ERP
sonar.projectName=Cristal_ERP

sonar.sources=services,erp-ui
sonar.exclusions=**/node_modules/**,**/*.exe,**/*.zip,**/invoices/**kubectl cluster-info
