sonar.host.url=http://127.0.0.1:9000
sonar.token=squ_3a3ca58540fec929f52ef0fb2999530910e2ac93

sonar.projectKey=Cristal_ERP
sonar.projectName=Cristal_ERP


sonar.sources=services

sonar.exclusions=**/node_modules/**,**/*.exe,**/*.zip