apiVersion: v1
kind: Secret
metadata:
  name: repo-cristal-ssh
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: git@github.com:Syrine-BEN-ANAYA/Cristal_ERP.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
    NhAAAAAwEAAQAAAgEAqwuwkHbcps7VZFHyNPhFUVy7WULdjRGFb2Cfqa0qsGzesg0VT2VQ
    rgX9dkDMpeC9Ymrn1APbcAzPw/KvAQL27eWm5uecat7poCezkRN9wEwyFUvYZrftBVdAaA
    CHZjGpjm4xWllkUq89y8XPfqW7x1RuyYowO7VzUz7/DZnd4JUw/GDeYF3p5fR8IphH6Ugs
    hznspumI1IAZ3PfBwCgJOgWV+Q56m0QvbV/qthYWde9XU5/8OlF8/ynKNVMXWPFG84kdqk
    McSeumAVJKxRUYmESk9Oonl+VtYKzUFYbxqwBK6Rb4hzsnwhh3EEchTZ3IQMhaC/hHOl4F
    gPbLF8h9v5DM7hAFnU0UI6GbqfmXCf7fX+HirLNJ5MmxA4qYPBnaA07NvehUCtDP3ycASK
    88bBTkQa8OKf0u602L16Ae/v/9vIw3W68GAgrOHRsbE+o+MxN+XBliGdcFvFlBhurTDVP7
    CUrTDSnWG+BBx5EjrDoYFgFB67dmq8x97iSj2D+/9ateTqH3eKoB2npxa7msOv60QZ4sEX
    dIYhlJ5h8jS84E4+4aGB7bRR2CNn6/MklqXHuU0k9epHK7LkrBC4NfCxvbUkBC+8Gjy+89
    cDakYDbdPpSGiirBDUgOCKJkzKcrfcRyrlRaQKKkP5KJb4PH4bPpdXBXjLA4Zx+XwZgMPl
    sAAAdIMyZKYTMmSmEAAAAHc3NoLXJzYQAAAgEAqwuwkHbcps7VZFHyNPhFUVy7WULdjRGF
    b2Cfqa0qsGzesg0VT2VQrgX9dkDMpeC9Ymrn1APbcAzPw/KvAQL27eWm5uecat7poCezkR
    N9wEwyFUvYZrftBVdAaACHZjGpjm4xWllkUq89y8XPfqW7x1RuyYowO7VzUz7/DZnd4JUw
    /GDeYF3p5fR8IphH6UgshznspumI1IAZ3PfBwCgJOgWV+Q56m0QvbV/qthYWde9XU5/8Ol
    F8/ynKNVMXWPFG84kdqkMcSeumAVJKxRUYmESk9Oonl+VtYKzUFYbxqwBK6Rb4hzsnwhh3
    EEchTZ3IQMhaC/hHOl4FgPbLF8h9v5DM7hAFnU0UI6GbqfmXCf7fX+HirLNJ5MmxA4qYPB
    naA07NvehUCtDP3ycASK88bBTkQa8OKf0u602L16Ae/v/9vIw3W68GAgrOHRsbE+o+MxN+
    XBliGdcFvFlBhurTDVP7CUrTDSnWG+BBx5EjrDoYFgFB67dmq8x97iSj2D+/9ateTqH3eK
    oB2npxa7msOv60QZ4sEXdIYhlJ5h8jS84E4+4aGB7bRR2CNn6/MklqXHuU0k9epHK7LkrB
    C4NfCxvbUkBC+8Gjy+89cDakYDbdPpSGiirBDUgOCKJkzKcrfcRyrlRaQKKkP5KJb4PH4b
    PpdXBXjLA4Zx+XwZgMPlsAAAADAQABAAACACdJzJkqTD2ehcKA1icXneh16eyzYKtuCl3O
    bm4tggA7SZ3RRoNRrMoEQzd94+P4Ltgj4TNAXY+rya9jF5KeaTS0yvT/31xm7nfklqjstr
    ZMajadEMxrU+yloXwiHve40Y8PPZPYs6QQb5vWSHZ5QBwlhzsQ3Epiv+YvsqsfnCjha/qU
    j4/IEplI4piZrO7nLp8zDWo7ezwAXrB0UlM+fvwOW2f1TPFMJK61WPbRNQCK5N6nAWst24
    3KvhEokFTUOu1moeNBfgZ2s89a5STG1zrmjZNaE5Ue1FRf7mkxcWJLc2l95sE9M8EwGG0r
    QXmQE/bZbmGQel/sR8xbI8RHP6a4TOT/AJccRNcgy55+gPVk4F4gOuGytiq4fW5gqHVoGq
    YZh9ILtZpOVArxCzi0T/TpYkHQLTTuRDJ3zE+FQD1MLj1MR+PZQOQY1vbw6enDFYHocsdr
    99zzznr/bfT21cU+CPYYacsmBMsPikV/qIR99NUnsikh4gnOghOOaWjm2u6sF8nQ09jcl+
    Y/gS75AmCYCw9thrCq+VLWAhXdl+Bp3goFufU8NwgVLaQID6a61Eptu0AsmfVVXymdpPiM
    iAZepTId/gxIai8gm/DmmzVYqY5oOqsRDlVn+LiVIDlxDj8w672BV0ijEa7rqs0YkVToco
    Nj3WVXquv/J/0beYA5AAABAQCZKuJkp7FsZpEPwWQjkOIm4Se2TknZsN4CAN5rgbR8N17H
    uMj0UyCJwDKTwGfZ8Ya8GHWskGBytH+LPCDLcp2jcyFAWfxXLMxXUWpS2UtEp219nyH5GO
    iC223nE+qJIjc774Lhdcf2FehXnn34uvwMYWl1HjlUDvX0tFexCeH+c4FCLu3OQYWSRTD1
    dWp1N7TtKcIl80mhQOIBUbicg2z/x77o2s2SggpBmBa1rFRB+vnxaInW3gAjpUyVIuNlAi
    c6cMhQ8z+RGo7rlYZCqMr2zXps/ObeKrjCUWnuMH630bvifeVTglGYXvdLFuaELz0pW67+
    2GuaEqsOHcSCU443AAABAQDRb7qxDeybmaudl1qkONAOAfd1Gi9I9tpwqa1C6fUdSCJfo3
    XT78OzwLeba+JDp/DSt5udeaQA4ulow5I0Wt3MIsty87pXBwNHWDx77flssZEjMla/Nn5T
    yIDp5He9WuYnD7MHyOFKsrY+wUMLHzlBfhEwhIGOfmMu3+8p8JVyEYMwmWknMJCU07Ap2V
    MQwDDDhrE1NVdpOUc9nYOpbLXr4t9qPSVP271uLOt1yArQf32M5xqjZiRDzZMQrPNw8cl0
    /QbxTFSiJrPZBebhoWAvFhVJj+5GJ9zRZKpdI9DVrxUFewcK+W3clAtC0wsC61XmLKSUWP
    ENBxB3nClyORFjAAABAQDREunSXEDbCruJJxc8r0UtGID2g8UTu2hP02lTQZLiJDzH2T8i
    TNOELX9CwdX/AJxC6UsFBVkSt5eJxRgZUQpqdf6ViExe6decm/L5LKq1v+fkxa8i0/OKmG
    4j1QNT9V3yVq9o1mVAy9lEHcniO3Gpfh5ZdFE4QJwSaG86SUqJY1tO9ln4A9X9RiEkRxJS
    Y7Wi2BEeWQ+Mwy9PiWNtFkllB2niJzs799jEF/3KT+ut9Xg9vIoxExLfHnb/tDGfnAQjYH
    H6F5joF5Wg8TvCIy9PLetAApoG6ON9NxqbMEHRnD1/MAEPW3eBQpFcwJd7KmzxBsCUAwJN
    OzmGB9Ex7mypAAAAEmFyZ29jZEBjcmlzdGFsLWVycA==
    -----END OPENSSH PRIVATE KEY-----