apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: erp-system

resources:
  - namespace.yaml
  - mongo-svc.yaml
  - auth-service.yaml
  - core-service.yaml
  - api-gateway.yaml
  - frontend.yaml
  - sonarqube.yaml
  - prometheus-config.yaml

# Pour les images locales
images:
  - name: auth-service
    newName: auth-service
    newTag: latest
  - name: core-service
    newName: core-service
    newTag: latest
  - name: api-gateway
    newName: api-gateway
    newTag: latest
  - name: erp-ui
    newName: erp-ui
    newTag: latest