name: CI-CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  security-events: write   
  actions: read             

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  

      - name: Build Docker images
        run: docker compose build

      - name: Run Trivy vulnerability scanner (non-blocking)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
          exit-code: '0'
      
      
      - name: Upload Trivy results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v4 
        with:
          sarif_file: 'trivy-results.sarif'
        continue-on-error: true  

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.Docker_username }}
          password: ${{ secrets.DockerHub_TOKEN }}

      - name: Push images to Docker Hub
        run: |
          docker tag auth-service:latest syrinebenanaya/auth-service:latest
          docker tag core-service:latest syrinebenanaya/core-service:latest
          docker tag api-gateway:latest syrinebenanaya/api-gateway:latest
          docker tag erp-ui:latest syrinebenanaya/erp-ui:latest
          
          docker push syrinebenanaya/auth-service:latest
          docker push syrinebenanaya/core-service:latest
          docker push syrinebenanaya/api-gateway:latest
          docker push syrinebenanaya/erp-ui:latest

  cd:
    needs: ci
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to production
        run: |
          echo "✅ Déploiement automatique vers la production"
          echo "Pull des dernières images depuis Docker Hub"
          echo "Redémarrage des services avec docker-compose"
          # ssh user@serveur "cd /app && docker-compose pull && docker-compose up -d"
          # .github/workflows/ci-cd.yml (ajout après push Docker Hub)
